# Generated by Django 4.2.8 on 2023-12-10 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="map",
            name="pgm_file",
            field=models.FileField(upload_to="map_files/"),
        ),
        migrations.AlterField(
            model_name="map",
            name="yaml_file",
            field=models.FileField(upload_to="map_files/"),
        ),
    ]
